### ISSUE TITLE
Some feedbacks

### ISSUE THREAD

**Issue by oushujun** [marbl/ModDotPlot#1]
Hi Alex,

Great tool! Congratulations!!
While using it, I found several places that could benefit from more clarification and slight modifications.
1. The relationship between `-w` and `-d` is not very clear. 
2. In the bed file, `query_name` and `reference_name` are all replaced by the `-p` value. Can it be the original sequence names?
3. Line 34 of `mod_identity.py` is hard coded to `perID*100 >= 80`; can you make it customizable to allow reporting lower identity regions?
4. The `mod_identity.py` script can only run on one sequence? Can it take the entire genome?
5. The `plot.r` script requires a folder named `results` in the working directory; otherwise, it will run into errors.
6. The `plot.r` script requires `ggplot2, dplyr, scales, RColorBrewer, data.table, cowplot, glue, argparse` packages installed in R.

Thanks!
Shujun

**Comment by alexsweeten** [comment]
Hi Shujun. Thanks for the feedback, and I'm so sorry for the (super) late reply!

> The relationship between -w and -d is not very clear.

I agree. I have renamed `-w` to `-r`, referring to the resolution of the dotplot. Essentially this represents how many chunks to divide the sequence up into for comparison. 

> In the bed file, query_name and reference_name are all replaced by the -p value. Can it be the original sequence names?

Fixed in afc0344e3669b50df30f48560dbbccc689012236

> Line 34 of mod_identity.py is hard coded to perID*100 >= 80; can you make it customizable to allow reporting lower identity regions?

Fixed in afc0344e3669b50df30f48560dbbccc689012236. This is now adjustable via the `-id` command.

> The mod_identity.py script can only run on one sequence? Can it take the entire genome?

I have refactored `parse_fasta` to utilize pysam. This will generate a bed file for each header sequence in the input fasta. 

> The plot.r script requires a folder named results in the working directory; otherwise, it will run into errors.

I plan to substitute the Rscript with an alternative in Python. This will reduce the number of dependencies required, and also unify with the interactive component of Mod.Plot!

Thanks again! I hope all is well in Columbus :)

**Comment by oushujun** [comment]
Thank you, Alex! All is well here :)
