### ISSUE TITLE
Nothing in the output figure

### ISSUE THREAD

**Issue by jiadong324** [marbl/ModDotPlot#32]
Dear author,

Thanks for developing this nice visualization tool! 

I am trying to make a plot between two sequences. The dotplot below is obtained with simple k-mer matches. 
<img width="2778" alt="image" src="https://github.com/user-attachments/assets/e9b2545a-31b2-4f89-b5dd-63a3ccfe23ec">

But when I use moddotplot for these two sequences, I got the figure below. This is my command ```moddotplot static -f NA12877_pat-0000377_chr22.fa --no-hist --no-bed -o dotplot --compare```

![NA12877_pat-0000377_CHM13-chr22_distal](https://github.com/user-attachments/assets/8c516ffe-2842-41a7-baf9-6f12a3326588)

Is this the parameter issues or something else?

**Comment by alexsweeten** [comment]
Hi @jiadong324,

Sorry for the late response! While I don't have your sequences in front of me, my best guess is that this is likely a result of one fasta being upper case, and the other being lower case. I've since patched this #33 

Please update to v0.8.5 and try again. If it's still outputting a blank plot, please let me know!

- Alex

**Comment by jiadong324** [comment]
@alexsweeten Thanks, it works now with the latest version. 

I also tried ```--grid``` with ```--compare-only```, it generates all pairwise comparison as individual figures. If I understand correctly, this option should generate a grid like figure including all the sequence comparisons.
